"""Canonical mapping of event_type strings to eight high-level categories

Every event emitted by the bot has a free-form `event_type` string; this
module groups those strings into the eight `EventCategory` values
(`LIFECYCLE`, `OFFER`, `PRICING`, `WALLET`, `EXCHANGE`, `RISK`, `SYSTEM`,
`COIN`) so the GUI can offer coarse filters without knowing every specific
name. `categorize_event(event_type)` is used by `api_server` for filtering
and by `doctor` / `runtime_monitor` for health rollups.

Key responsibilities:
    - Define `EventCategory` as a `StrEnum` (with a fallback for older Pythons)
    - Maintain the authoritative event_type → category mapping
    - Default unknown event types to `SYSTEM` rather than failing

The map is additive — adding new event types to the codebase is a matter of
appending rows here. Existing event names never change.
"""

from __future__ import annotations

try:
    from enum import StrEnum
except ImportError:
    from enum import Enum
    class StrEnum(str, Enum):
        pass


class EventCategory(StrEnum):
    """Canonical event categories."""
    LIFECYCLE = "lifecycle"   # bot start/stop/startup sync
    OFFER = "offer"           # offer create/cancel/fill/requote/refresh
    PRICING = "pricing"       # price fetch/validation/limits/arb
    WALLET = "wallet"         # wallet sync/health/address
    EXCHANGE = "exchange"     # dexie/splash posting
    RISK = "risk"             # circuit breakers/recovery/guards
    SYSTEM = "system"         # db/config/monitor/diagnostics
    COIN = "coin"             # coin prep/topup/reconcile/split


# Mapping from existing event_type strings to canonical category.
# Events not in this map default to SYSTEM.
_EVENT_CATEGORY_MAP = {
    # ---- LIFECYCLE ----
    "bot_starting": EventCategory.LIFECYCLE,
    "bot_started": EventCategory.LIFECYCLE,
    "bot_stopped": EventCategory.LIFECYCLE,
    "bot_loop_init": EventCategory.LIFECYCLE,
    "bot_loop_exit": EventCategory.LIFECYCLE,
    "startup_sync": EventCategory.LIFECYCLE,
    "startup_sync_done": EventCategory.LIFECYCLE,
    "startup_sync_failed": EventCategory.LIFECYCLE,
    "startup_wallet_sync": EventCategory.LIFECYCLE,
    "startup_wallet_result": EventCategory.LIFECYCLE,
    "startup_offer_recovery": EventCategory.LIFECYCLE,
    "startup_offer_linking": EventCategory.LIFECYCLE,
    "startup_coins_critical": EventCategory.LIFECYCLE,
    "startup_spares_low": EventCategory.LIFECYCLE,
    "startup_coins_unavailable": EventCategory.LIFECYCLE,
    "startup_coin_recheck": EventCategory.LIFECYCLE,
    "startup_orphan_cleanup": EventCategory.LIFECYCLE,
    "startup_orphan_cleanup_failed": EventCategory.LIFECYCLE,
    "startup_full_reconcile": EventCategory.LIFECYCLE,
    "startup_baseline_price": EventCategory.LIFECYCLE,
    "startup_baseline_failed": EventCategory.LIFECYCLE,
    "startup_baseline_zero": EventCategory.LIFECYCLE,
    "startup_recovery_failed": EventCategory.LIFECYCLE,
    "startup_reconcile_link_failed": EventCategory.LIFECYCLE,
    "startup_grace": EventCategory.LIFECYCLE,
    "startup_test": EventCategory.LIFECYCLE,
    "bot_start_blocked_watch_only": EventCategory.LIFECYCLE,
    "cycle_start": EventCategory.LIFECYCLE,
    "cycle_complete": EventCategory.LIFECYCLE,
    "loop_error": EventCategory.LIFECYCLE,
    "database_init": EventCategory.LIFECYCLE,
    "bot_health_watch_started": EventCategory.LIFECYCLE,
    "bot_health_watch_exit": EventCategory.LIFECYCLE,
    "bot_health_watch_error": EventCategory.LIFECYCLE,
    "bot_health_topup_recovered": EventCategory.LIFECYCLE,
    "preflight_run": EventCategory.LIFECYCLE,
    "preflight_blocked": EventCategory.LIFECYCLE,
    "preflight_error": EventCategory.LIFECYCLE,
    "app_shutdown": EventCategory.LIFECYCLE,
    "server_started": EventCategory.LIFECYCLE,
    "server_shutdown": EventCategory.LIFECYCLE,
    "daemon_start": EventCategory.LIFECYCLE,
    "daemon_stop": EventCategory.LIFECYCLE,
    "fresh_start_cleanup_failed": EventCategory.LIFECYCLE,
    "session_fresh_start_failed": EventCategory.LIFECYCLE,

    # ---- OFFER ----
    "offer_created": EventCategory.OFFER,
    "offer_create_failed": EventCategory.OFFER,
    "offer_cancelled": EventCategory.OFFER,
    "offer_cancelled_detected": EventCategory.OFFER,
    "offer_expired": EventCategory.OFFER,
    "offer_expired_detected": EventCategory.OFFER,
    "offer_filled": EventCategory.OFFER,
    "offer_failed": EventCategory.OFFER,
    "offer_retry": EventCategory.OFFER,
    "offer_hint_retry": EventCategory.OFFER,
    "offer_duplicate": EventCategory.OFFER,
    "offer_mempool_conflict": EventCategory.OFFER,
    "offer_insufficient_balance": EventCategory.OFFER,
    "offer_coin_link": EventCategory.OFFER,
    "offer_coin_link_error": EventCategory.OFFER,
    "offer_link_error": EventCategory.OFFER,
    "offer_requested_snapshot_fail": EventCategory.OFFER,
    "offer_size_snapshot_fail": EventCategory.OFFER,
    "offers_cancel_pending": EventCategory.OFFER,
    "offers_cancelled": EventCategory.OFFER,
    "offers_expired": EventCategory.OFFER,
    "offers_recovered": EventCategory.OFFER,
    "parallel_offer_error": EventCategory.OFFER,
    "ladder_interrupted": EventCategory.OFFER,
    "ladder_parallel": EventCategory.OFFER,
    "ladder_parallel_done": EventCategory.OFFER,
    "create_skip": EventCategory.OFFER,
    "create_skip_requoted": EventCategory.OFFER,
    "dry_run": EventCategory.OFFER,
    "expiring_soon": EventCategory.OFFER,
    "requoting": EventCategory.OFFER,
    "requote_start": EventCategory.OFFER,
    "requote_done": EventCategory.OFFER,
    "requote_skip": EventCategory.OFFER,
    "requote_skip_recovery": EventCategory.OFFER,
    "requote_batch_cancel": EventCategory.OFFER,
    "requote_batch_create": EventCategory.OFFER,
    "requote_batch_done": EventCategory.OFFER,
    "requote_coins_freed": EventCategory.OFFER,
    "requote_coins_slow": EventCategory.OFFER,
    "requote_interrupted": EventCategory.OFFER,
    "requote_no_cancel": EventCategory.OFFER,
    "requote_cold_start": EventCategory.OFFER,
    "requote_cold_start_queued": EventCategory.OFFER,
    "requote_no_spares": EventCategory.OFFER,
    "requote_creating": EventCategory.OFFER,
    "requote_create_failed": EventCategory.OFFER,
    "requote_cancel": EventCategory.OFFER,
    "requote_upgrade": EventCategory.OFFER,
    "requote_spare_coins": EventCategory.OFFER,
    "requote_cancel_failed_stop": EventCategory.OFFER,
    "emergency_requote": EventCategory.OFFER,
    "emergency_requote_backoff": EventCategory.OFFER,
    "emergency_requote_done": EventCategory.OFFER,
    "emergency_requote_no_progress": EventCategory.OFFER,
    "emergency_requote_partial": EventCategory.OFFER,
    "emergency_requote_retry_eligible": EventCategory.OFFER,
    "emergency_requote_waiting_for_cancel_settle": EventCategory.OFFER,
    "fills_detected": EventCategory.OFFER,
    "fill_protect": EventCategory.OFFER,
    "fill_verified": EventCategory.OFFER,
    "fill_rejected": EventCategory.OFFER,
    "fill_unverified": EventCategory.OFFER,
    "fill_verify_cancelled_alive": EventCategory.OFFER,
    "fill_no_details": EventCategory.OFFER,
    "fill_no_coin_id": EventCategory.OFFER,
    "fill_record_failed": EventCategory.OFFER,
    "fill_cache_miss_recovered": EventCategory.OFFER,
    "fill_dexie_still_open": EventCategory.OFFER,
    "fill_dexie_expired": EventCategory.OFFER,
    "fill_dexie_coin_mismatch": EventCategory.OFFER,
    "fill_dexie_trade_mismatch": EventCategory.OFFER,
    "fill_local_retire_failed": EventCategory.OFFER,
    "fill_wallet_closed_nonfill": EventCategory.OFFER,
    "fill_wallet_still_open": EventCategory.OFFER,
    "fills_purged": EventCategory.OFFER,
    "pnl_matched": EventCategory.OFFER,
    "pnl_unmatched_fills": EventCategory.OFFER,
    "pnl_skipped_zero_fills": EventCategory.OFFER,
    "round_trip_matched": EventCategory.OFFER,
    "round_trip_match_failed": EventCategory.OFFER,
    "fill_tracker_init": EventCategory.OFFER,
    "fill_tracker_reset": EventCategory.OFFER,
    "fill_rate_update_failed": EventCategory.OFFER,
    "known_ids_pruned": EventCategory.OFFER,
    "batched_cancel": EventCategory.OFFER,
    "batched_cancel_done": EventCategory.OFFER,
    "cancel_retries": EventCategory.OFFER,
    "cancel_all": EventCategory.OFFER,
    "cancel_all_batch": EventCategory.OFFER,
    "cancel_all_batch_error": EventCategory.OFFER,
    "cancel_all_batched": EventCategory.OFFER,
    "cancel_all_blocked_live": EventCategory.OFFER,
    "cancel_all_direct": EventCategory.OFFER,
    "cancel_all_done": EventCategory.OFFER,
    "cancel_failed_queued": EventCategory.OFFER,
    "cancel_result": EventCategory.OFFER,
    "cancel_retry_exhausted": EventCategory.OFFER,
    "cancel_retry_failed": EventCategory.OFFER,
    "cancel_retry_success": EventCategory.OFFER,
    "cancel_start": EventCategory.OFFER,
    "defensive_cancel_start": EventCategory.OFFER,
    "defensive_cancel_skip": EventCategory.OFFER,
    "mempool_defensive_cancel_done": EventCategory.OFFER,
    "mempool_defensive_cancel_deferred_pending_cancel_settle": EventCategory.OFFER,
    "mempool_preconfirm_defensive_cancel_done": EventCategory.OFFER,
    "mempool_preconfirm_cancel_deferred_pending_cancel_settle": EventCategory.OFFER,
    "pending_cancel_settle_retry_queued": EventCategory.OFFER,
    "pending_cancel_settle_retry_exhausted": EventCategory.OFFER,
    "orphan_cleanup_start": EventCategory.OFFER,
    "orphan_cleanup_done": EventCategory.OFFER,
    "orphan_cleanup_found": EventCategory.OFFER,
    "orphan_cleanup": EventCategory.OFFER,
    "orphan_cleanup_error": EventCategory.OFFER,
    "orphan_cleanup_failed": EventCategory.OFFER,
    "orphan_freed": EventCategory.OFFER,
    "orphan_cancel_batch": EventCategory.OFFER,
    "orphan_cancel_batch_result": EventCategory.OFFER,
    "housekeeping": EventCategory.OFFER,
    "housekeeping_orphan_cleanup": EventCategory.OFFER,
    "housekeeping_sanity_failed": EventCategory.OFFER,
    "sage_offer_cleanup": EventCategory.OFFER,
    "sage_offer_cleanup_db": EventCategory.OFFER,
    "sage_cleanup_failed": EventCategory.OFFER,
    "sage_single_offer_test": EventCategory.OFFER,
    "sage_receive_side_hidden": EventCategory.OFFER,
    "spacescan_fill_confirmed": EventCategory.OFFER,
    "spacescan_self_spend": EventCategory.OFFER,
    "spacescan_phantom_detected": EventCategory.OFFER,
    "sage_fill_backfill": EventCategory.OFFER,
    "offer_lifecycle_transition": EventCategory.OFFER,

    # ---- PRICING ----
    "price_lookup": EventCategory.PRICING,
    "price_found": EventCategory.PRICING,
    "price_error": EventCategory.PRICING,
    "price_guard": EventCategory.PRICING,
    "price_strategy": EventCategory.PRICING,
    "no_price": EventCategory.PRICING,
    "amm_drift_detected": EventCategory.PRICING,
    "amm_drift_requote_triggered": EventCategory.PRICING,
    "mempool_imminent_wake": EventCategory.PRICING,
    "mempool_price_confirmed": EventCategory.PRICING,
    "mempool_price_move": EventCategory.PRICING,
    "mempool_price_move_below_trigger": EventCategory.PRICING,
    "mempool_preconfirm_cancel_below_trigger": EventCategory.PRICING,
    "mempool_swap_detected": EventCategory.PRICING,
    "tibet_swap_detected": EventCategory.PRICING,
    "tibet_error": EventCategory.PRICING,
    "post_snipe_reprice": EventCategory.PRICING,
    "post_snipe_price": EventCategory.PRICING,
    "post_create_market_observed": EventCategory.PRICING,
    "dynamic_limits_init": EventCategory.PRICING,
    "orderbook_error": EventCategory.PRICING,
    "orderbook_refresh": EventCategory.PRICING,
    "balance_discrepancy_xch": EventCategory.PRICING,
    "balance_discrepancy_cat": EventCategory.PRICING,

    # ---- WALLET ----
    "wallet_sync": EventCategory.WALLET,
    "wallet_sync_live_again": EventCategory.WALLET,
    "wallet_switch": EventCategory.WALLET,
    "wallet_address_detected": EventCategory.WALLET,
    "wallet_address_error": EventCategory.WALLET,
    "wallet_address_failed": EventCategory.WALLET,
    "chia_unhealthy": EventCategory.WALLET,
    "chia_still_unhealthy": EventCategory.WALLET,
    "chia_recovered": EventCategory.WALLET,
    "sage_fingerprint_changed_externally": EventCategory.WALLET,
    "sage_fingerprint_restored": EventCategory.WALLET,
    "chia_restart": EventCategory.WALLET,
    "chia_restart_needed": EventCategory.WALLET,
    "chia_startup": EventCategory.WALLET,
    "health_monitor": EventCategory.WALLET,
    "health_monitor_exit": EventCategory.WALLET,
    "health_error": EventCategory.WALLET,
    "sage_startup": EventCategory.WALLET,
    "sage_unknown_status_code": EventCategory.WALLET,
    "sage_unknown_status_str": EventCategory.WALLET,
    "sage_change_address_set": EventCategory.WALLET,
    "sage_change_address_failed": EventCategory.WALLET,
    "cat_discovery": EventCategory.WALLET,
    "cat_mapping_mismatch": EventCategory.WALLET,
    "cat_selected": EventCategory.WALLET,
    "rpc_error_in_coins": EventCategory.WALLET,

    # ---- EXCHANGE ----
    "dexie_recovery": EventCategory.EXCHANGE,
    "dexie_repost": EventCategory.EXCHANGE,
    "dexie_flush": EventCategory.EXCHANGE,
    "dexie_flush_start": EventCategory.EXCHANGE,
    "dexie_flush_result": EventCategory.EXCHANGE,
    "dexie_flush_parallel": EventCategory.EXCHANGE,
    "dexie_recovery_failed": EventCategory.EXCHANGE,
    "dexie_repost_failed": EventCategory.EXCHANGE,
    "dexie_repost_background": EventCategory.EXCHANGE,
    "dexie_repost_done": EventCategory.EXCHANGE,
    "dexie_repost_plan": EventCategory.EXCHANGE,
    "dexie_repost_queued": EventCategory.EXCHANGE,
    "dexie_posted": EventCategory.EXCHANGE,
    "dexie_post_failed": EventCategory.EXCHANGE,
    "dexie_error": EventCategory.EXCHANGE,
    "dexie_disabled": EventCategory.EXCHANGE,
    "dexie_no_id": EventCategory.EXCHANGE,
    "dexie_db_update_failed": EventCategory.EXCHANGE,
    "dexie_pruned": EventCategory.EXCHANGE,
    "dexie_offer_detail_failed": EventCategory.EXCHANGE,
    "dexie_fingerprints_cleared": EventCategory.EXCHANGE,
    "splash_node_auto": EventCategory.EXCHANGE,
    "splash_node_auto_failed": EventCategory.EXCHANGE,
    "splash_node_auto_download": EventCategory.EXCHANGE,
    "splash_node_started": EventCategory.EXCHANGE,
    "splash_node_stopped": EventCategory.EXCHANGE,
    "splash_node_crashed": EventCategory.EXCHANGE,
    "splash_node_running": EventCategory.EXCHANGE,
    "splash_node_launching": EventCategory.EXCHANGE,
    "splash_node_exited": EventCategory.EXCHANGE,
    "splash_node_stale": EventCategory.EXCHANGE,
    "splash_node_max_restarts": EventCategory.EXCHANGE,
    "splash_node_not_found": EventCategory.EXCHANGE,
    "splash_node_output": EventCategory.EXCHANGE,
    "splash_node_webhook": EventCategory.EXCHANGE,
    "splash_node_no_webhook": EventCategory.EXCHANGE,
    "splash_node_launch_error": EventCategory.EXCHANGE,
    "splash_node_stop_error": EventCategory.EXCHANGE,
    "splash_node_download_error": EventCategory.EXCHANGE,
    "splash_node_download_failed": EventCategory.EXCHANGE,
    "splash_node": EventCategory.EXCHANGE,
    "splash_receive_exit": EventCategory.EXCHANGE,
    "splash_receive_error": EventCategory.EXCHANGE,
    "splash_receive_parser": EventCategory.EXCHANGE,
    "splash_receive_view_error": EventCategory.EXCHANGE,
    "splash_received": EventCategory.EXCHANGE,
    "splash_flush": EventCategory.EXCHANGE,
    "splash_flush_start": EventCategory.EXCHANGE,
    "splash_flush_result": EventCategory.EXCHANGE,
    "splash_flush_parallel": EventCategory.EXCHANGE,
    "splash_repost_done": EventCategory.EXCHANGE,
    "splash_repost_queued": EventCategory.EXCHANGE,
    "splash_posted": EventCategory.EXCHANGE,
    "splash_post_failed": EventCategory.EXCHANGE,
    "splash_error": EventCategory.EXCHANGE,
    "splash_setup": EventCategory.EXCHANGE,
    "splash_reset": EventCategory.EXCHANGE,
    "splash_db_error": EventCategory.EXCHANGE,
    "splash_pruned": EventCategory.EXCHANGE,
    "splash_unhealthy": EventCategory.EXCHANGE,
    "splash_recovered": EventCategory.EXCHANGE,
    "splash_fingerprints_cleared": EventCategory.EXCHANGE,
    "repost_error": EventCategory.EXCHANGE,

    # ---- RISK ----
    "circuit_breaker": EventCategory.RISK,
    "circuit_breaker_tripped": EventCategory.RISK,
    "circuit_breaker_cleared": EventCategory.RISK,
    "recovery_mode_enter": EventCategory.RISK,
    "recovery_mode_exit": EventCategory.RISK,
    "recovery_create_wait": EventCategory.RISK,
    "recovery_create_stall_escalation": EventCategory.RISK,
    "ladder_overlap_skip": EventCategory.RISK,
    "ladder_thread_timeout": EventCategory.RISK,
    "stale_wallet_requote_blocked": EventCategory.RISK,
    "stale_wallet_create_blocked": EventCategory.RISK,
    "mass_disappearance_guard": EventCategory.RISK,
    "mass_disappearance_accepted": EventCategory.RISK,
    "probe_launch": EventCategory.RISK,
    "probe_launch_status": EventCategory.RISK,
    "probe_confirmed": EventCategory.RISK,
    "probe_confirmed_status": EventCategory.RISK,
    "probe_retry": EventCategory.RISK,
    "probe_retry_status": EventCategory.RISK,
    "probe_hold_status": EventCategory.RISK,
    "probe_max_retries": EventCategory.RISK,
    "probe_timeout_status": EventCategory.RISK,
    "probe_visibility_wait": EventCategory.RISK,
    "probe_wallet_poll_failed": EventCategory.RISK,
    "sniper_recovery": EventCategory.RISK,
    "sniper_recovery_failed": EventCategory.RISK,
    "sniper_recovery_pause": EventCategory.RISK,
    "sniper_cleanup": EventCategory.RISK,
    "sniper_cleanup_failed": EventCategory.RISK,
    "sniper_cleanup_wait": EventCategory.RISK,
    "sniper_cleaned": EventCategory.RISK,
    "sniper_disabled": EventCategory.RISK,
    "sniper_no_swap": EventCategory.RISK,
    "sniper_fired": EventCategory.RISK,
    "sniper_created": EventCategory.RISK,
    "sniper_failed": EventCategory.RISK,
    "sniper_bad_amount": EventCategory.RISK,
    "sniper_dry_run": EventCategory.RISK,
    "sniper_pruned": EventCategory.RISK,
    "sniper_dexie_failed": EventCategory.RISK,
    "sniper_splash_failed": EventCategory.RISK,
    "boost_stale_protection": EventCategory.RISK,
    "boost_crossref_failed": EventCategory.RISK,
    "gap_closer_skip_busy": EventCategory.RISK,
    "gap_closer_recovery": EventCategory.RISK,
    "gap_closer_recovery_failed": EventCategory.RISK,
    "gap_closer_activated": EventCategory.RISK,
    "gap_closer_deactivated": EventCategory.RISK,
    "gap_closer_activate_error": EventCategory.RISK,
    "gap_closer_activate_failed": EventCategory.RISK,
    "gap_closer_step": EventCategory.RISK,
    "gap_closer_arbed": EventCategory.RISK,
    "gap_closer_created": EventCategory.RISK,
    "gap_closer_create_failed": EventCategory.RISK,
    "gap_closer_refresh": EventCategory.RISK,
    "gap_closer_refresh_failed": EventCategory.RISK,
    "gap_closer_refreshed": EventCategory.RISK,
    "gap_closer_pruned": EventCategory.RISK,
    "gap_closer_convergence": EventCategory.RISK,
    "gap_closer_cascade": EventCategory.RISK,
    "gap_closer_bad_amount": EventCategory.RISK,
    "gap_closer_dry_run": EventCategory.RISK,
    "cascade_batch": EventCategory.RISK,
    "cascade_create_failed": EventCategory.RISK,
    "cascade_no_coins": EventCategory.RISK,
    "collateral_advisory": EventCategory.RISK,
    "advisory_failed": EventCategory.RISK,
    "position_inherited": EventCategory.RISK,

    # ---- SYSTEM ----
    "db_cleanup_start": EventCategory.SYSTEM,
    "db_cleanup_done": EventCategory.SYSTEM,
    "db_cleanup_failed": EventCategory.SYSTEM,
    "db_migration": EventCategory.SYSTEM,
    "db_error": EventCategory.SYSTEM,
    "backup": EventCategory.SYSTEM,
    "config_migration": EventCategory.SYSTEM,
    "config_migration_failed": EventCategory.SYSTEM,
    "config_error": EventCategory.SYSTEM,
    "config_changed": EventCategory.SYSTEM,
    "config_live": EventCategory.SYSTEM,
    "config_validated": EventCategory.SYSTEM,
    "smart_defaults": EventCategory.SYSTEM,
    "trading_pace": EventCategory.SYSTEM,
    "pace_record_failed": EventCategory.SYSTEM,
    "intel_error": EventCategory.SYSTEM,
    "connectivity_recovery": EventCategory.SYSTEM,
    "inventory_update_failed": EventCategory.SYSTEM,
    "snapshot_failed": EventCategory.SYSTEM,
    "spacescan_api_error": EventCategory.SYSTEM,
    "spacescan_balance_error": EventCategory.SYSTEM,
    "spacescan_balance_ok": EventCategory.SYSTEM,
    "spacescan_balance_parse_error": EventCategory.SYSTEM,
    "spacescan_balance_skip": EventCategory.SYSTEM,
    "spacescan_budget_exceeded": EventCategory.SYSTEM,
    "spacescan_coin_not_found": EventCategory.SYSTEM,
    "spacescan_connection_error": EventCategory.SYSTEM,
    "spacescan_disabled": EventCategory.SYSTEM,
    "spacescan_error": EventCategory.SYSTEM,
    "spacescan_fill_ambiguous": EventCategory.SYSTEM,
    "spacescan_import_failed": EventCategory.SYSTEM,
    "spacescan_no_coin_id": EventCategory.SYSTEM,
    "spacescan_not_found": EventCategory.SYSTEM,
    "spacescan_rate_limited": EventCategory.SYSTEM,
    "spacescan_server_error": EventCategory.SYSTEM,
    "spacescan_setup": EventCategory.SYSTEM,
    "spacescan_timeout": EventCategory.SYSTEM,
    "spacescan_verify_failed": EventCategory.SYSTEM,

    # ---- COIN ----
    "coin_watcher_started": EventCategory.COIN,
    "coin_watcher_baseline": EventCategory.COIN,
    "coin_watcher_error": EventCategory.COIN,
    "coin_watcher_exit": EventCategory.COIN,
    "coin_reconciliation": EventCategory.COIN,
    "coin_settle_wait": EventCategory.COIN,
    "coin_ops_skip_recovery": EventCategory.COIN,
    "coin_created": EventCategory.COIN,
    "coin_designated": EventCategory.COIN,
    "coin_freed": EventCategory.COIN,
    "coin_freed_on_expire": EventCategory.COIN,
    "coin_gone": EventCategory.COIN,
    "coin_locked": EventCategory.COIN,
    "coin_spent": EventCategory.COIN,
    "coin_upserted": EventCategory.COIN,
    "coin_selected": EventCategory.COIN,
    "coin_select_error": EventCategory.COIN,
    "coin_select_none": EventCategory.COIN,
    "coin_select_skip": EventCategory.COIN,
    "coin_select_db_unavailable": EventCategory.COIN,
    "coin_select_snapshot_fail": EventCategory.COIN,
    "coin_inventory": EventCategory.COIN,
    "coin_readiness": EventCategory.COIN,
    "coin_sync_summary": EventCategory.COIN,
    "coin_count_failed": EventCategory.COIN,
    "coin_count_retry": EventCategory.COIN,
    "coin_count_retry_ok": EventCategory.COIN,
    "coin_health_cooldown": EventCategory.COIN,
    "coin_health_ok": EventCategory.COIN,
    "coin_health_trigger": EventCategory.COIN,
    "coin_ids_failed": EventCategory.COIN,
    "coin_ids_fallback": EventCategory.COIN,
    "coin_ids_locked": EventCategory.COIN,
    "coin_ids_mode": EventCategory.COIN,
    "coin_ids_no_preferred_tier": EventCategory.COIN,
    "coin_ids_verify_failed": EventCategory.COIN,
    "coin_lock_timeout": EventCategory.COIN,
    "coin_mgr_fingerprint": EventCategory.COIN,
    "coin_mgr_fingerprint_cli_fail": EventCategory.COIN,
    "coin_mgr_fingerprint_rpc_fail": EventCategory.COIN,
    "coin_mgr_no_fingerprint": EventCategory.COIN,
    "coin_persist_failed": EventCategory.COIN,
    "coin_persist_skip_gone": EventCategory.COIN,
    "coin_reuse_detected": EventCategory.COIN,
    "coin_reuse_giving_up": EventCategory.COIN,
    "coin_sanity_error": EventCategory.COIN,
    "coin_sanity_ok": EventCategory.COIN,
    "coin_sanity_warning": EventCategory.COIN,
    "coin_split_manual": EventCategory.COIN,
    "coin_state_change": EventCategory.COIN,
    "coin_snapshot_before_fail": EventCategory.COIN,
    "coin_snapshot_multi": EventCategory.COIN,
    "coin_snapshot_poll_fail": EventCategory.COIN,
    "coins_gone_summary": EventCategory.COIN,
    "coins_skipped_no_id": EventCategory.COIN,
    "designation_fallback": EventCategory.COIN,
    "low_coins_adaptive": EventCategory.COIN,
    "low_coins_free": EventCategory.COIN,
    "low_coins_total": EventCategory.COIN,
    "locked_coin_count_failed": EventCategory.COIN,
    "no_reserve_available": EventCategory.COIN,
    "ensure_reserve_error": EventCategory.COIN,
    "coin_prep_trigger": EventCategory.COIN,
    "coin_prep_started": EventCategory.COIN,
    "coin_prep_failed": EventCategory.COIN,
    "coin_prep_complete": EventCategory.COIN,
    "coin_prep_config": EventCategory.COIN,
    "coin_prep_exception": EventCategory.COIN,
    "coin_prep_gate": EventCategory.COIN,
    "coin_prep_ungate": EventCategory.COIN,
    "coin_prep_ungate_error": EventCategory.COIN,
    "coin_prep_kill": EventCategory.COIN,
    "coin_prep_kill_failed": EventCategory.COIN,
    "coin_prep_killed": EventCategory.COIN,
    "coin_prep_missing": EventCategory.COIN,
    "coin_prep_multiplier": EventCategory.COIN,
    "coin_prep_start_failed": EventCategory.COIN,
    "coin_prep_bot_stopped": EventCategory.COIN,
    "coin_prep_balance_check_failed": EventCategory.COIN,
    "coin_prep_cancelled_ids": EventCategory.COIN,
    "coin_prep_stdout": EventCategory.COIN,
    "coin_prep_stderr": EventCategory.COIN,
    "topup_trigger": EventCategory.COIN,
    "topup_timeout": EventCategory.COIN,
    "topup_started": EventCategory.COIN,
    "topup_stopped": EventCategory.COIN,
    "topup_stop_requested": EventCategory.COIN,
    "topup_error": EventCategory.COIN,
    "topup_no_action": EventCategory.COIN,
    "topup_inventory": EventCategory.COIN,
    "topup_inventory_changed": EventCategory.COIN,
    "topup_coins_locked": EventCategory.COIN,      # kept for backward compat
    "topup_split_blocked": EventCategory.COIN,     # tier low but reserve guard refused
    "topup_tiers_adequate": EventCategory.COIN,    # all tiers above threshold (normal)
    "topup_deferred_offer_rebuild_priority": EventCategory.COIN,
    "topup_waiting_for_source": EventCategory.COIN,
    "topup_backoff_reset": EventCategory.COIN,
    "topup_wait_sync": EventCategory.COIN,
    "topup_waiting": EventCategory.COIN,
    "topup_wallet_unsynced": EventCategory.COIN,
    "topup_zero_transient": EventCategory.COIN,
    "topup_xch_sniper": EventCategory.COIN,
    "topup_cat_sniper": EventCategory.COIN,
    "tier_size_drift": EventCategory.COIN,
    "tier_size_drift_topup_started": EventCategory.COIN,
    "tier_size_drift_topup_deferred": EventCategory.COIN,
    "tier_size_drift_waiting_for_source": EventCategory.COIN,
    "health_topup_trigger": EventCategory.COIN,
    "reconcile_done": EventCategory.COIN,
    "reconcile_error": EventCategory.COIN,
    "reconcile_skip": EventCategory.COIN,
    "reconcile_locked": EventCategory.COIN,
    "reconcile_locked_error": EventCategory.COIN,
    "reconcile_link_offers": EventCategory.COIN,
    "reconcile_link_failed": EventCategory.COIN,
    "reconcile_direct_link": EventCategory.COIN,
    "reconcile_direct_link_failed": EventCategory.COIN,
    "coinset_ready": EventCategory.COIN,
    "coinset_init": EventCategory.COIN,
    "coinset_init_skipped": EventCategory.COIN,
    "coinset_init_error": EventCategory.COIN,
    "coinset_init_failed": EventCategory.COIN,
    "coinset_error": EventCategory.COIN,
    "coinset_api_error": EventCategory.COIN,
    "coinset_http_error": EventCategory.COIN,
    "coinset_query": EventCategory.COIN,
    "coinset_fallback": EventCategory.COIN,
    "coinset_fallback_failed": EventCategory.COIN,
    "coinset_lookup_error": EventCategory.COIN,
    "coinset_recovered": EventCategory.COIN,
    "coinset_unhealthy": EventCategory.COIN,
    "reservation_acquired": EventCategory.COIN,
    "reservation_released": EventCategory.COIN,
    "reservation_expired": EventCategory.COIN,
    "reservation_release_error": EventCategory.COIN,

    # ---- Cycle step events (LIFECYCLE) ----
    "step1b_intel": EventCategory.LIFECYCLE,
    "step2_breakers": EventCategory.LIFECYCLE,
    "step3_sync": EventCategory.LIFECYCLE,
    "step4_fills": EventCategory.LIFECYCLE,
    "step6_inventory": EventCategory.LIFECYCLE,
    "step7_refresh": EventCategory.LIFECYCLE,
    "step7_skipped": EventCategory.LIFECYCLE,
    "step9_requote": EventCategory.LIFECYCLE,
    "step9_done": EventCategory.LIFECYCLE,
    "step10_create": EventCategory.LIFECYCLE,
    "step12_coins": EventCategory.LIFECYCLE,
    "step15_gui": EventCategory.LIFECYCLE,

    # ---- Watcher events ----
    "watcher_started": EventCategory.WALLET,
    "watcher_disabled": EventCategory.WALLET,
    "watcher_exit": EventCategory.WALLET,
    "watcher_error": EventCategory.WALLET,
    "watcher_wake": EventCategory.WALLET,
    "watcher_thread_error": EventCategory.WALLET,
}


def categorize_event(event_type: str) -> EventCategory:
    """Return the canonical category for an event type.

    Falls back to SYSTEM for unmapped events.
    """
    return _EVENT_CATEGORY_MAP.get(event_type, EventCategory.SYSTEM)


def get_category_map() -> dict:
    """Return the full event-to-category mapping (for diagnostics/API)."""
    return dict(_EVENT_CATEGORY_MAP)
