"""Sync release metadata files from a version string.

The release workflow calls this before PyInstaller runs so the app-visible
version, Windows PE metadata, and bundle metadata all agree with the tag.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


VERSION_RE = re.compile(r"^v?(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?$")


def _parse_version(version: str) -> tuple[str, tuple[int, int, int, int]]:
    match = VERSION_RE.fullmatch(version.strip())
    if not match:
        raise ValueError("version must be numeric semver like 1.2.3 or v1.2.3")
    major, minor, patch, build = match.groups()
    normalized = f"{int(major)}.{int(minor)}.{int(patch)}"
    parts = (int(major), int(minor), int(patch), int(build or 0))
    return normalized, parts


def _version_info(version: str, parts: tuple[int, int, int, int]) -> str:
    dotted = ".".join(str(part) for part in parts)
    tuple_text = ", ".join(str(part) for part in parts)
    return f"""# Windows PE version resource for CATalyst.exe
#
# Generated by scripts/sync_release_metadata.py.
# PyInstaller reads this file via the `version=` parameter in EXE().

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({tuple_text}),
    prodvers=({tuple_text}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [
          StringStruct(u'CompanyName',      u'MonkeyZoo'),
          StringStruct(u'FileDescription',  u'CATalyst - Chia AMM Liquidity Bot'),
          StringStruct(u'FileVersion',      u'{dotted}'),
          StringStruct(u'InternalName',     u'CATalyst'),
          StringStruct(u'LegalCopyright',   u'Copyright (c) 2026 MonkeyZoo'),
          StringStruct(u'OriginalFilename', u'Catalyst.exe'),
          StringStruct(u'ProductName',      u'CATalyst'),
          StringStruct(u'ProductVersion',   u'{version}'),
        ]
      )
    ]),
    VarFileInfo([VarStruct(u'Translation', [0x0409, 1200])])
  ]
)
"""


def sync_release_metadata(root: Path, version: str) -> None:
    normalized, parts = _parse_version(version)

    version_file = root / "src" / "catalyst" / "_version.py"
    version_file.write_text(f'__version__ = "{normalized}"\n', encoding="utf-8")

    version_info = root / "version_info.txt"
    version_info.write_text(_version_info(normalized, parts), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="Release version, with or without v prefix")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root, used by tests and CI",
    )
    args = parser.parse_args()

    try:
        sync_release_metadata(args.root, args.version)
    except ValueError as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
